# Generated by Django 5.0.6 on 2024-07-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
    ]
